name: Java CI with Gradle

on:
  push:
    branches: [ feature/firstfeature ]
  pull_request:
    branches: [ feature/firstfeature ]

jobs:
  build:
    env:
        gradle.publish.key: ${{ secrets.GRADLE_KEY }}
        gradle.publish.secret: ${{ secrets.GRADLE_SECRET }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Configure git credentials & release version
      uses: OleksiyRudenko/gha-git-credentials@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - run: ./gradlew release -Prelease.useAutomaticVersion=true -x test 
    - name: save environment variables
      run: echo -e "\ngradle.publish.key=${{ secrets.GRADLE_KEY }}\ngradle.publish.secret=${{ secrets.GRADLE_SECRET }}" >> gradle.properties
    - name: publish plugin
      run: ./gradlew publishPlugins
